use std::fs;
use std::net::IpAddr;
use std::thread::sleep;
use std::time::Duration;

fn main() {
    let content = match fs::read_to_string("/etc/network/interfaces") {
        Ok(c) => c,
        Err(_) => return,
    };

    let mut nameservers: Vec<IpAddr> = Vec::new();

    for raw_line in content.lines() {
        let line = raw_line.split('#').next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }

        let mut tokens = line.split_whitespace();
        if let Some(directive) = tokens.next() {
            if directive == "dns-nameservers" || directive == "dns-nameserver" {
                for token in tokens {
                    if let Ok(ip) = token.parse::<IpAddr>() {
                        if !nameservers.contains(&ip) {
                            nameservers.push(ip);
                        }
                    }
                }
            }
        }
    }

    if nameservers.is_empty() {
        return;
    }

    let mut expected = String::with_capacity(256);
    expected.push_str("# Generated by openresolvconf\n");
    for ip in nameservers {
        expected.push_str(&format!("nameserver {ip}\n"));
    }

    let target_path = "/etc/resolv.conf";

    for _ in 0..5 {
        if fs::write(target_path, &expected).is_ok() {
            if let Ok(current) = fs::read_to_string(target_path) {
                if current == expected {
                    break;
                }
            }
        }
        sleep(Duration::from_secs(1));
    }
}
